///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Polarion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PolarionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bec37f0b-6dd8-44a9-92a2-ef938304f3db")]
    public partial class PolarionRepository : RepoGenBaseFolder
    {
        static PolarionRepository instance = new PolarionRepository();
        PolarionRepositoryFolders.LoginAppFolder _login;

        /// <summary>
        /// Gets the singleton class instance representing the PolarionRepository element repository.
        /// </summary>
        [RepositoryFolder("bec37f0b-6dd8-44a9-92a2-ef938304f3db")]
        public static PolarionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PolarionRepository() 
            : base("PolarionRepository", "/", null, 0, false, "bec37f0b-6dd8-44a9-92a2-ef938304f3db", ".\\RepositoryImages\\PolarionRepositorybec37f0b.rximgres")
        {
            _login = new PolarionRepositoryFolders.LoginAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bec37f0b-6dd8-44a9-92a2-ef938304f3db")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Login folder.
        /// </summary>
        [RepositoryFolder("9ac95ba9-0a98-46ec-80e3-8f0acc1cddd9")]
        public virtual PolarionRepositoryFolders.LoginAppFolder Login
        {
            get { return _login; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PolarionRepositoryFolders
    {
        /// <summary>
        /// The LoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("9ac95ba9-0a98-46ec-80e3-8f0acc1cddd9")]
        public partial class LoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jusernameInfo;
            RepoItemInfo _jpasswordInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _createInfo;
            RepoItemInfo _afunctionalorbehavioralrequirementtInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _somebodytagInfo;
            RepoItemInfo _shouldhaveInfo;
            RepoItemInfo _musthaveInfo;
            RepoItemInfo _savetocreatectrlplussInfo;
            RepoItemInfo _httppl1chzrh0298nbpolarionriaimageInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "/dom[@domain='pl1chzrh0298nb']", parentFolder, 30000, null, false, "9ac95ba9-0a98-46ec-80e3-8f0acc1cddd9", "")
            {
                _jusernameInfo = new RepoItemInfo(this, "JUsername", ".//input[#'j_username']", ".//input[#'j_username']", 30000, null, "6147a055-2e3b-4b35-9f3a-8f53f6091652");
                _jpasswordInfo = new RepoItemInfo(this, "JPassword", ".//input[#'j_password']", ".//input[#'j_password']", 30000, null, "2c3dc057-953f-42b6-9152-5bed6490eb4e");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//button[#'submitButton']", ".//button[#'submitButton']", 30000, null, "80334c63-d47b-4769-93db-b8cfea84032d");
                _createInfo = new RepoItemInfo(this, "CREATE", ".//div[#'gwt-debug-polarion-PortalBase-FlowPanel']//div[@title>'Quick Create - Create new']/span[@innertext='CREATE...']", ".//div[#'gwt-debug-polarion-PortalBase-FlowPanel']//span[@innertext='CREATE...']", 30000, null, "33d4f2c3-468d-470d-929a-f6491a15056e");
                _afunctionalorbehavioralrequirementtInfo = new RepoItemInfo(this, "AFunctionalOrBehavioralRequirementT", ".//div[#'quickCreateDialog']/div/div/div[8]/div/div/div[1]/div[3]/div/div[4]/?/?/div[@id='gwt-debug-polarion-rpe-preview-debug-id']/div/div/div[1]/div/div[2]/div[@id='polarion-rp-widget-content']/div/div[2]/span[@title>'A functional or behavioral']", ".//div[#'quickCreateDialog']//span[@title>'A functional or behavioral']", 30000, null, "06db9bc6-ef0c-4f26-aa47-88d143d9f464");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'_ui_form_layouter']/div/div/table/?/?/tr/td[2]/table//input[@type='text']", ".//div[#'_ui_form_layouter']//input[@type='text']", 30000, null, "18bc71a2-2c0c-4f40-965c-19595de6f1a6");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", ".//iframe[#'gwt-debug-polarion-rte-area-debug-id']/body", ".//iframe[#'gwt-debug-polarion-rte-area-debug-id']/body", 30000, null, "782d49f6-c44b-4be7-932e-aff7ecbfee24");
                _shouldhaveInfo = new RepoItemInfo(this, "ShouldHave", ".//td[#'FIELD_severity']//table/?/?/tr/td[3]/img[@title='Should Have']", ".//td[#'FIELD_severity']//img[@title='Should Have']", 30000, null, "d0c75e98-76f6-412c-94c3-c19609bef372");
                _musthaveInfo = new RepoItemInfo(this, "MustHave", "body/div[5]/div[2]/table/tbody/tr[1]/td[@innertext='Must Have']", ".//td[@innertext='Must Have']", 30000, null, "7083d624-9190-413f-a11e-e4b257c1993c");
                _savetocreatectrlplussInfo = new RepoItemInfo(this, "SaveToCreateCTRLPlusS", ".//table[#'_ui_toolbar']/?/?/tr/td[4]/table//td[@innertext='Save']", ".//table[#'_ui_toolbar']//td[@innertext='Save']", 30000, null, "ba5f2890-4aa3-468a-94ca-ae95235c4705");
                _httppl1chzrh0298nbpolarionriaimageInfo = new RepoItemInfo(this, "HttpPl1chzrh0298nbPolarionRiaImage", ".//div[#'gwt-debug-polarion-SideArea-BasePanel']/table/tbody/tr[1]//table/?/?/tr/td[1]/div[@title='Show Settings']/table//img[@src='http://pl1chzrh0298nb/polarion/ria/images/portal/lite_settings_off.svg']", ".//div[#'gwt-debug-polarion-SideArea-BasePanel']//img[@src='http://pl1chzrh0298nb/polarion/ria/images/portal/lite_settings_off.svg']", 30000, null, "87071c6c-4f8d-4d96-b321-517323bd5493");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'gwt-debug-polarion-SideArea-BasePanel']/div/table/tbody/tr[2]//div[@innertext='Logout']", ".//div[#'gwt-debug-polarion-SideArea-BasePanel']//div[@innertext='Logout']", 30000, null, "13821d96-c512-4225-9412-682196a5e9ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9ac95ba9-0a98-46ec-80e3-8f0acc1cddd9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9ac95ba9-0a98-46ec-80e3-8f0acc1cddd9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JUsername item.
            /// </summary>
            [RepositoryItem("6147a055-2e3b-4b35-9f3a-8f53f6091652")]
            public virtual Ranorex.InputTag JUsername
            {
                get
                {
                    return _jusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JUsername item info.
            /// </summary>
            [RepositoryItemInfo("6147a055-2e3b-4b35-9f3a-8f53f6091652")]
            public virtual RepoItemInfo JUsernameInfo
            {
                get
                {
                    return _jusernameInfo;
                }
            }

            /// <summary>
            /// The JPassword item.
            /// </summary>
            [RepositoryItem("2c3dc057-953f-42b6-9152-5bed6490eb4e")]
            public virtual Ranorex.InputTag JPassword
            {
                get
                {
                    return _jpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JPassword item info.
            /// </summary>
            [RepositoryItemInfo("2c3dc057-953f-42b6-9152-5bed6490eb4e")]
            public virtual RepoItemInfo JPasswordInfo
            {
                get
                {
                    return _jpasswordInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("80334c63-d47b-4769-93db-b8cfea84032d")]
            public virtual Ranorex.ButtonTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("80334c63-d47b-4769-93db-b8cfea84032d")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The CREATE item.
            /// </summary>
            [RepositoryItem("33d4f2c3-468d-470d-929a-f6491a15056e")]
            public virtual Ranorex.SpanTag CREATE
            {
                get
                {
                    return _createInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CREATE item info.
            /// </summary>
            [RepositoryItemInfo("33d4f2c3-468d-470d-929a-f6491a15056e")]
            public virtual RepoItemInfo CREATEInfo
            {
                get
                {
                    return _createInfo;
                }
            }

            /// <summary>
            /// The AFunctionalOrBehavioralRequirementT item.
            /// </summary>
            [RepositoryItem("06db9bc6-ef0c-4f26-aa47-88d143d9f464")]
            public virtual Ranorex.SpanTag AFunctionalOrBehavioralRequirementT
            {
                get
                {
                    return _afunctionalorbehavioralrequirementtInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AFunctionalOrBehavioralRequirementT item info.
            /// </summary>
            [RepositoryItemInfo("06db9bc6-ef0c-4f26-aa47-88d143d9f464")]
            public virtual RepoItemInfo AFunctionalOrBehavioralRequirementTInfo
            {
                get
                {
                    return _afunctionalorbehavioralrequirementtInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("18bc71a2-2c0c-4f40-965c-19595de6f1a6")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("18bc71a2-2c0c-4f40-965c-19595de6f1a6")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("782d49f6-c44b-4be7-932e-aff7ecbfee24")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("782d49f6-c44b-4be7-932e-aff7ecbfee24")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The ShouldHave item.
            /// </summary>
            [RepositoryItem("d0c75e98-76f6-412c-94c3-c19609bef372")]
            public virtual Ranorex.ImgTag ShouldHave
            {
                get
                {
                    return _shouldhaveInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ShouldHave item info.
            /// </summary>
            [RepositoryItemInfo("d0c75e98-76f6-412c-94c3-c19609bef372")]
            public virtual RepoItemInfo ShouldHaveInfo
            {
                get
                {
                    return _shouldhaveInfo;
                }
            }

            /// <summary>
            /// The MustHave item.
            /// </summary>
            [RepositoryItem("7083d624-9190-413f-a11e-e4b257c1993c")]
            public virtual Ranorex.TdTag MustHave
            {
                get
                {
                    return _musthaveInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The MustHave item info.
            /// </summary>
            [RepositoryItemInfo("7083d624-9190-413f-a11e-e4b257c1993c")]
            public virtual RepoItemInfo MustHaveInfo
            {
                get
                {
                    return _musthaveInfo;
                }
            }

            /// <summary>
            /// The SaveToCreateCTRLPlusS item.
            /// </summary>
            [RepositoryItem("ba5f2890-4aa3-468a-94ca-ae95235c4705")]
            public virtual Ranorex.TdTag SaveToCreateCTRLPlusS
            {
                get
                {
                    return _savetocreatectrlplussInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SaveToCreateCTRLPlusS item info.
            /// </summary>
            [RepositoryItemInfo("ba5f2890-4aa3-468a-94ca-ae95235c4705")]
            public virtual RepoItemInfo SaveToCreateCTRLPlusSInfo
            {
                get
                {
                    return _savetocreatectrlplussInfo;
                }
            }

            /// <summary>
            /// The HttpPl1chzrh0298nbPolarionRiaImage item.
            /// </summary>
            [RepositoryItem("87071c6c-4f8d-4d96-b321-517323bd5493")]
            public virtual Ranorex.ImgTag HttpPl1chzrh0298nbPolarionRiaImage
            {
                get
                {
                    return _httppl1chzrh0298nbpolarionriaimageInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpPl1chzrh0298nbPolarionRiaImage item info.
            /// </summary>
            [RepositoryItemInfo("87071c6c-4f8d-4d96-b321-517323bd5493")]
            public virtual RepoItemInfo HttpPl1chzrh0298nbPolarionRiaImageInfo
            {
                get
                {
                    return _httppl1chzrh0298nbpolarionriaimageInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("13821d96-c512-4225-9412-682196a5e9ec")]
            public virtual Ranorex.DivTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("13821d96-c512-4225-9412-682196a5e9ec")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
