///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Polarion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("4cc8e55b-9c12-4403-b5c0-a213f8bb58ce", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PolarionRepository repository.
        /// </summary>
        public static PolarionRepository repo = PolarionRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://pl1chzrh0298nb/polarion/#/project/SiemensDemo/workitems' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://pl1chzrh0298nb/polarion/#/project/SiemensDemo/workitems", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.JUsername' at 133;8.", repo.Login.JUsernameInfo, new RecordItemIndex(1));
            repo.Login.JUsername.Click("133;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lVoillat' with focus on 'Login.JUsername'.", repo.Login.JUsernameInfo, new RecordItemIndex(2));
            repo.Login.JUsername.PressKeys("lVoillat");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.JPassword' at 75;12.", repo.Login.JPasswordInfo, new RecordItemIndex(3));
            repo.Login.JPassword.Click("75;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'Login.JPassword'.", repo.Login.JPasswordInfo, new RecordItemIndex(4));
            repo.Login.JPassword.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.SubmitButton' at 75;19.", repo.Login.SubmitButtonInfo, new RecordItemIndex(5));
            repo.Login.SubmitButton.Click("75;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.CREATE' at 32;12.", repo.Login.CREATEInfo, new RecordItemIndex(6));
            repo.Login.CREATE.Click("32;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.CREATE' at 27;10.", repo.Login.CREATEInfo, new RecordItemIndex(7));
            repo.Login.CREATE.Click("27;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.AFunctionalOrBehavioralRequirementT' at 53;7.", repo.Login.AFunctionalOrBehavioralRequirementTInfo, new RecordItemIndex(8));
            repo.Login.AFunctionalOrBehavioralRequirementT.Click("53;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.Text' at 165;22.", repo.Login.TextInfo, new RecordItemIndex(9));
            repo.Login.Text.Click("165;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'SysReq for Ranorex' with focus on 'Login.Text'.", repo.Login.TextInfo, new RecordItemIndex(10));
            repo.Login.Text.PressKeys("SysReq for Ranorex");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.ShouldHave' at 8;8.", repo.Login.ShouldHaveInfo, new RecordItemIndex(11));
            repo.Login.ShouldHave.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.MustHave' at 41;12.", repo.Login.MustHaveInfo, new RecordItemIndex(12));
            repo.Login.MustHave.Click("41;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.SomeBodyTag' at 243;51.", repo.Login.SomeBodyTagInfo, new RecordItemIndex(13));
            repo.Login.SomeBodyTag.Click("243;51");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'System Requirement for Ranorex and Jenkins' with focus on 'Login.SomeBodyTag'.", repo.Login.SomeBodyTagInfo, new RecordItemIndex(14));
            repo.Login.SomeBodyTag.PressKeys("System Requirement for Ranorex and Jenkins");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.SaveToCreateCTRLPlusS' at 11;14.", repo.Login.SaveToCreateCTRLPlusSInfo, new RecordItemIndex(15));
            repo.Login.SaveToCreateCTRLPlusS.Click("11;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.HttpPl1chzrh0298nbPolarionRiaImage' at 18;6.", repo.Login.HttpPl1chzrh0298nbPolarionRiaImageInfo, new RecordItemIndex(16));
            repo.Login.HttpPl1chzrh0298nbPolarionRiaImage.Click("18;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.HttpPl1chzrh0298nbPolarionRiaImage' at 26;9.", repo.Login.HttpPl1chzrh0298nbPolarionRiaImageInfo, new RecordItemIndex(17));
            repo.Login.HttpPl1chzrh0298nbPolarionRiaImage.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Login.Logout' at 26;4.", repo.Login.LogoutInfo, new RecordItemIndex(18));
            repo.Login.Logout.Click("26;4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
